# Generated by Django 4.2.5 on 2023-10-14 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
