# Generated by Django 4.2.5 on 2023-10-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_orders_address_orders_phonenumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('buyer',)},
        ),
    ]
