# Generated by Django 4.2.5 on 2023-10-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_orders_payment_alter_orders_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='time_order',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
