# Generated by Django 4.2.5 on 2023-10-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='item',
            name='remaining_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
