# Generated by Django 4.2.5 on 2023-10-21 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_alter_feedback_options_item_remaining_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('user',)},
        ),
    ]
